#!/bin/bash
#
# Command 'pkexec' wrapper.
# Executes the command retaining the $PWD instead of changing to /root.
#
# Requires a simple helper script 'cmdindir' that changes directory
# back to $PWD first and then executes the command.
#

/usr/bin/pkexec cmdindir "$PWD" "$@"
